baseURL = "http://www.henson.me"
languageCode = "en-us"
title = "Jacob Henson"
theme = "hensonme.hugo.theme"
publishDir = docs
pygmentsUseClasses = "true"
pygmentsStyle = "monokai"
sectionPagesMenu = "main"

[[menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Resume"
    weight = 0
    # identifier = "resume"
    url = "/resume/"
[[menu.main]]
    name = "Posts"
    weight = -50
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "About Me"
    weight = 2
    identifier = "about-me"
    url = "/about-me/"
